### PR TITLE
Fix cordova icon in service catalog view

### PR DESCRIPTION
**Pull request by JameelB**
## Description
The cordova icon in the service catalog view does not render correctly. Use the icon added by this [PR](https://github.com/openshift/origin-web-console/pull/2850) in the OpenShift web console. 

## Progress
- [x] Add an imageUrl to the apb's metadata and point it to the cordova icon in the OpenShift web console.

## Screenshots
image

image

image

### CODE REVIEW

**Comment by JameelB** [comment]
ping @sedroche

**Comment by sedroche** [comment]
@JameelB Looks great. Was there an icon update too?
icon -> fa-icon?

**Comment by JameelB** [comment]
@sedroche no there wasn't an icon update since it will be using the imageUrl instead of the icon class.

**Comment by sedroche** [comment]
[This](https://github.com/aerogearcatalog/cordova-app-apb/blob/e25cb47ca4bab941d00c11eba223b5439c8c5883/apb.yml#L10) should be `fa-icon` I think though can you update it in this PR too?

**Comment by JameelB** [comment]
@sedroche Think you're thinking about `font-icon` will change it to that. :+1:

**Comment by sedroche** [comment]
yes, sorry, thanks

**Pull request merged**
